name: Building

on: [push, pull_request]
    
jobs:
  Build:
    runs-on: ubuntu-latest
    name: Building Source
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Zip
        # if: github.event_name == 'push' || github.ref == 'refs/heads/master'
        run: zip -r OIAPI.zip .
        
      - name: Get current commit information
        run: |
          COMMIT_INFO=$(git log -1 --pretty=format:"%H %an %ae %s")
          echo "$COMMIT_INFO"

      - name: Up Load Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OIAPI
          path: OIAPI.zip
