name: Building

on: [push, pull_request]
    
jobs:
  Build:
    runs-on: ubuntu-latest
    name: Building Source
    outputs:
      commit_info: ${{ steps.get_current_commit.outputs.commit_info }}
      version: ${{ steps.extract_version.outputs.version }}   
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Zip
        # if: github.event_name == 'push' || github.ref == 'refs/heads/master'
        run: zip -r OIAPI.zip .
        
      - name: Get current commit information
        id: get_current_commit
        run: |
          COMMIT_INFO=$(git log -1 --pretty=format:"%H %an %ae %s")
          echo "commit_info=$COMMIT_INFO" >> $GITHUB_OUTPUT
      
      - name: Extract version from commit message
        id: extract_version
        shell: pwsh
        run: |
          echo ${{ steps.get_current_commit.outputs.commit_info }}
          $pattern = 'v\d+(\.\d+)*'
          $VERSION = 1.0.0.0
          if (${{ steps.get_current_commit.outputs.commit_info }} -match $pattern) {
             $VERSION = $Matches[0]
           }
           echo "version=$VERSION" >> $GITHUB_OUTPUT
           echo $VERSION

      - name: Up Load Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OIAPI
          path: OIAPI.zip
