name: Building

on: [push, pull_request]
    
jobs:
  Build:
    runs-on: ubuntu-latest
    name: Building Source
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Zip
        #if: github.event_name == 'push' || github.ref == 'refs/heads/master'
        run: zip -r OIAPI.zip .

      - name: Up Load Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OIAPI
          path: OIAPI.zip
          
      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: 更新tag
        #if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git tag -f V1.0.0.0
          git push -f origin V1.0.0.0

      - name: 发布插件包
        #if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          tag: V1.0.0.0
          name: "最新版本"
          body: |
             # 更新
          artifact: OIAPI.zip
          allowUpdates: true
          removeArtifacts: true
