name: Build ZIP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create ZIP file
      run: zip -r repo.zip .
    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v2
      with:
        name: repo-source
        path: repo.zip
